// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MilestoneSchema = {
    properties: {
        milestone_date: {
            type: 'string',
            format: 'date-time',
            title: 'Milestone Date'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        status: {
            '$ref': '#/components/schemas/MilestoneStatus',
            default: '正常'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['milestone_date', 'description', 'id', 'project_id', 'created_at', 'updated_at'],
    title: 'Milestone'
} as const;

export const MilestoneCreateSchema = {
    properties: {
        milestone_date: {
            type: 'string',
            format: 'date-time',
            title: 'Milestone Date'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        status: {
            '$ref': '#/components/schemas/MilestoneStatus',
            default: '正常'
        }
    },
    type: 'object',
    required: ['milestone_date', 'description'],
    title: 'MilestoneCreate'
} as const;

export const MilestoneStatusSchema = {
    type: 'string',
    enum: ['正常', '延期', '完成'],
    title: 'MilestoneStatus'
} as const;

export const MilestoneUpdateSchema = {
    properties: {
        milestone_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Milestone Date'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MilestoneStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'MilestoneUpdate'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PermissionCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        resource: {
            type: 'string',
            title: 'Resource'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        description: {
            type: 'string',
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name', 'resource', 'action'],
    title: 'PermissionCreate'
} as const;

export const PermissionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        resource: {
            type: 'string',
            title: 'Resource'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['id', 'name', 'resource', 'action'],
    title: 'PermissionPublic'
} as const;

export const PermissionUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        resource: {
            type: 'string',
            title: 'Resource'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        description: {
            type: 'string',
            title: 'Description'
        }
    },
    type: 'object',
    title: 'PermissionUpdate'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProgressSchema = {
    properties: {
        description: {
            type: 'string',
            title: 'Description'
        },
        progress_type: {
            '$ref': '#/components/schemas/ProgressType',
            default: '日进展'
        },
        tracking_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Tracking User Id'
        },
        progress_date: {
            type: 'string',
            format: 'date-time',
            title: 'Progress Date'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['description', 'tracking_user_id', 'id', 'project_id', 'created_at', 'updated_at'],
    title: 'Progress'
} as const;

export const ProgressCreateSchema = {
    properties: {
        description: {
            type: 'string',
            title: 'Description'
        },
        progress_type: {
            '$ref': '#/components/schemas/ProgressType',
            default: '日进展'
        },
        tracking_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Tracking User Id'
        },
        progress_date: {
            type: 'string',
            format: 'date-time',
            title: 'Progress Date'
        }
    },
    type: 'object',
    required: ['description', 'tracking_user_id'],
    title: 'ProgressCreate'
} as const;

export const ProgressTypeSchema = {
    type: 'string',
    enum: ['日进展', '周进展'],
    title: 'ProgressType'
} as const;

export const ProgressUpdateSchema = {
    properties: {
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        progress_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ProgressType'
                },
                {
                    type: 'null'
                }
            ]
        },
        tracking_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tracking User Id'
        },
        progress_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Progress Date'
        }
    },
    type: 'object',
    title: 'ProgressUpdate'
} as const;

export const ProjectSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        project_type: {
            type: 'string',
            title: 'Project Type'
        },
        location: {
            type: 'string',
            title: 'Location'
        },
        contract_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contract Amount'
        },
        background: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Background'
        },
        import_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Import Time'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        products: {
            items: {
                '$ref': '#/components/schemas/ProjectProduct'
            },
            type: 'array',
            title: 'Products',
            default: []
        },
        role_assignments: {
            items: {
                '$ref': '#/components/schemas/RoleAssignment'
            },
            type: 'array',
            title: 'Role Assignments',
            default: []
        },
        milestones: {
            items: {
                '$ref': '#/components/schemas/Milestone'
            },
            type: 'array',
            title: 'Milestones',
            default: []
        },
        progresses: {
            items: {
                '$ref': '#/components/schemas/Progress'
            },
            type: 'array',
            title: 'Progresses',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'project_type', 'location', 'id', 'created_at', 'updated_at'],
    title: 'Project'
} as const;

export const ProjectCountByLocationSchema = {
    properties: {
        location: {
            type: 'string',
            title: 'Location'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['location', 'count'],
    title: 'ProjectCountByLocation'
} as const;

export const ProjectCountByProductSchema = {
    properties: {
        product: {
            type: 'string',
            title: 'Product'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['product', 'count'],
    title: 'ProjectCountByProduct'
} as const;

export const ProjectCountByTypeSchema = {
    properties: {
        project_type: {
            type: 'string',
            title: 'Project Type'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['project_type', 'count'],
    title: 'ProjectCountByType'
} as const;

export const ProjectCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        project_type: {
            type: 'string',
            title: 'Project Type'
        },
        location: {
            type: 'string',
            title: 'Location'
        },
        contract_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contract Amount'
        },
        background: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Background'
        },
        import_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Import Time'
        },
        products: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/ProjectProductCreate'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Products',
            default: []
        },
        role_assignments: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/RoleAssignmentCreate'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role Assignments',
            default: []
        },
        milestones: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/MilestoneCreate'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Milestones',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'project_type', 'location'],
    title: 'ProjectCreate'
} as const;

export const ProjectProductSchema = {
    properties: {
        product_name: {
            type: 'string',
            title: 'Product Name'
        },
        product_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Amount'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['product_name', 'id', 'project_id', 'created_at'],
    title: 'ProjectProduct'
} as const;

export const ProjectProductCreateSchema = {
    properties: {
        product_name: {
            type: 'string',
            title: 'Product Name'
        },
        product_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Amount'
        }
    },
    type: 'object',
    required: ['product_name'],
    title: 'ProjectProductCreate'
} as const;

export const ProjectStatisticsSchema = {
    properties: {
        by_location: {
            items: {
                '$ref': '#/components/schemas/ProjectCountByLocation'
            },
            type: 'array',
            title: 'By Location'
        },
        by_product: {
            items: {
                '$ref': '#/components/schemas/ProjectCountByProduct'
            },
            type: 'array',
            title: 'By Product'
        },
        by_type: {
            items: {
                '$ref': '#/components/schemas/ProjectCountByType'
            },
            type: 'array',
            title: 'By Type'
        },
        total_projects: {
            type: 'integer',
            title: 'Total Projects'
        },
        total_contract_amount: {
            type: 'number',
            title: 'Total Contract Amount'
        }
    },
    type: 'object',
    required: ['by_location', 'by_product', 'by_type', 'total_projects', 'total_contract_amount'],
    title: 'ProjectStatistics'
} as const;

export const ProjectUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        project_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Type'
        },
        location: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        },
        contract_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contract Amount'
        },
        background: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Background'
        },
        import_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Import Time'
        },
        products: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/ProjectProductCreate'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Products'
        },
        role_assignments: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/RoleAssignmentCreate'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role Assignments'
        },
        milestones: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/MilestoneCreate'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Milestones'
        }
    },
    type: 'object',
    title: 'ProjectUpdate'
} as const;

export const RoleAssignmentSchema = {
    properties: {
        role_name: {
            type: 'string',
            title: 'Role Name'
        },
        user_name: {
            type: 'string',
            title: 'User Name'
        },
        user_email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Email'
        },
        user_phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Phone'
        },
        user_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['role_name', 'user_name', 'id', 'project_id', 'created_at'],
    title: 'RoleAssignment'
} as const;

export const RoleAssignmentCreateSchema = {
    properties: {
        role_name: {
            type: 'string',
            title: 'Role Name'
        },
        user_name: {
            type: 'string',
            title: 'User Name'
        },
        user_email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Email'
        },
        user_phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Phone'
        },
        user_description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Description'
        }
    },
    type: 'object',
    required: ['role_name', 'user_name'],
    title: 'RoleAssignmentCreate'
} as const;

export const RoleCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'RoleCreate'
} as const;

export const RolePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        permissions: {
            items: {
                '$ref': '#/components/schemas/PermissionPublic'
            },
            type: 'array',
            title: 'Permissions',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'RolePublic'
} as const;

export const RoleUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        }
    },
    type: 'object',
    title: 'RoleUpdate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;