// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, RbacGetRolesWorkingResponse, RbacCreateRoleData, RbacCreateRoleResponse, RbacGetPermissionsWorkingResponse, RbacCreatePermissionData, RbacCreatePermissionResponse, RbacUpdatePermissionData, RbacUpdatePermissionResponse, RbacDeletePermissionData, RbacDeletePermissionResponse, RbacUpdateRoleData, RbacUpdateRoleResponse, RbacDeleteRoleData, RbacDeleteRoleResponse, RbacAssignPermissionToRoleData, RbacAssignPermissionToRoleResponse, RbacRemovePermissionFromRoleData, RbacRemovePermissionFromRoleResponse, RbacGetRolePermissionsData, RbacGetRolePermissionsResponse, RbacAssignRoleToUserData, RbacAssignRoleToUserResponse, RbacRemoveRoleFromUserData, RbacRemoveRoleFromUserResponse, RbacGetUserRolesData, RbacGetUserRolesResponse, RbacGetUserPermissionsData, RbacGetUserPermissionsResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class RbacService {
    /**
     * Get Roles Working
     * 获取所有角色 - 直接查询版本
     * @returns RolePublic Successful Response
     * @throws ApiError
     */
    public static getRolesWorking(): CancelablePromise<RbacGetRolesWorkingResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/rbac/roles'
        });
    }
    
    /**
     * Create Role
     * 创建角色
     * @param data The data for the request.
     * @param data.name
     * @param data.description
     * @returns RolePublic Successful Response
     * @throws ApiError
     */
    public static createRole(data: RbacCreateRoleData): CancelablePromise<RbacCreateRoleResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/rbac/roles',
            query: {
                name: data.name,
                description: data.description
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Permissions Working
     * 获取所有权限
     * @returns PermissionPublic Successful Response
     * @throws ApiError
     */
    public static getPermissionsWorking(): CancelablePromise<RbacGetPermissionsWorkingResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/rbac/permissions'
        });
    }
    
    /**
     * Create Permission
     * 创建权限
     * @param data The data for the request.
     * @param data.name
     * @param data.resource
     * @param data.action
     * @param data.description
     * @returns PermissionPublic Successful Response
     * @throws ApiError
     */
    public static createPermission(data: RbacCreatePermissionData): CancelablePromise<RbacCreatePermissionResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/rbac/permissions',
            query: {
                name: data.name,
                resource: data.resource,
                action: data.action,
                description: data.description
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Permission
     * 更新权限
     * @param data The data for the request.
     * @param data.permissionId
     * @param data.name
     * @param data.resource
     * @param data.action
     * @param data.description
     * @returns PermissionPublic Successful Response
     * @throws ApiError
     */
    public static updatePermission(data: RbacUpdatePermissionData): CancelablePromise<RbacUpdatePermissionResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/rbac/permissions/{permission_id}',
            path: {
                permission_id: data.permissionId
            },
            query: {
                name: data.name,
                resource: data.resource,
                action: data.action,
                description: data.description
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Permission
     * 删除权限
     * @param data The data for the request.
     * @param data.permissionId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static deletePermission(data: RbacDeletePermissionData): CancelablePromise<RbacDeletePermissionResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/rbac/permissions/{permission_id}',
            path: {
                permission_id: data.permissionId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Role
     * 更新角色
     * @param data The data for the request.
     * @param data.roleId
     * @param data.name
     * @param data.description
     * @returns RolePublic Successful Response
     * @throws ApiError
     */
    public static updateRole(data: RbacUpdateRoleData): CancelablePromise<RbacUpdateRoleResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/rbac/roles/{role_id}',
            path: {
                role_id: data.roleId
            },
            query: {
                name: data.name,
                description: data.description
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Role
     * 删除角色
     * @param data The data for the request.
     * @param data.roleId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static deleteRole(data: RbacDeleteRoleData): CancelablePromise<RbacDeleteRoleResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/rbac/roles/{role_id}',
            path: {
                role_id: data.roleId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Assign Permission To Role
     * 为角色分配权限
     * @param data The data for the request.
     * @param data.roleId
     * @param data.permissionId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static assignPermissionToRole(data: RbacAssignPermissionToRoleData): CancelablePromise<RbacAssignPermissionToRoleResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/rbac/roles/{role_id}/permissions/{permission_id}',
            path: {
                role_id: data.roleId,
                permission_id: data.permissionId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Remove Permission From Role
     * 从角色移除权限
     * @param data The data for the request.
     * @param data.roleId
     * @param data.permissionId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static removePermissionFromRole(data: RbacRemovePermissionFromRoleData): CancelablePromise<RbacRemovePermissionFromRoleResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/rbac/roles/{role_id}/permissions/{permission_id}',
            path: {
                role_id: data.roleId,
                permission_id: data.permissionId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Role Permissions
     * 获取角色的权限
     * @param data The data for the request.
     * @param data.roleId
     * @returns PermissionPublic Successful Response
     * @throws ApiError
     */
    public static getRolePermissions(data: RbacGetRolePermissionsData): CancelablePromise<RbacGetRolePermissionsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/rbac/roles/{role_id}/permissions',
            path: {
                role_id: data.roleId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Assign Role To User
     * 为用户分配角色
     * @param data The data for the request.
     * @param data.userId
     * @param data.roleId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static assignRoleToUser(data: RbacAssignRoleToUserData): CancelablePromise<RbacAssignRoleToUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/rbac/users/{user_id}/roles/{role_id}',
            path: {
                user_id: data.userId,
                role_id: data.roleId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Remove Role From User
     * 从用户移除角色
     * @param data The data for the request.
     * @param data.userId
     * @param data.roleId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static removeRoleFromUser(data: RbacRemoveRoleFromUserData): CancelablePromise<RbacRemoveRoleFromUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/rbac/users/{user_id}/roles/{role_id}',
            path: {
                user_id: data.userId,
                role_id: data.roleId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get User Roles
     * 获取用户的角色
     * @param data The data for the request.
     * @param data.userId
     * @returns RolePublic Successful Response
     * @throws ApiError
     */
    public static getUserRoles(data: RbacGetUserRolesData): CancelablePromise<RbacGetUserRolesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/rbac/users/{user_id}/roles',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get User Permissions
     * 获取用户的权限
     * @param data The data for the request.
     * @param data.userId
     * @returns PermissionPublic Successful Response
     * @throws ApiError
     */
    public static getUserPermissions(data: RbacGetUserPermissionsData): CancelablePromise<RbacGetUserPermissionsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/rbac/users/{user_id}/permissions',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}