// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type Milestone = {
    milestone_date: string;
    description: string;
    status?: MilestoneStatus;
    id: string;
    project_id: string;
    created_at: string;
    updated_at: string;
};

export type MilestoneCreate = {
    milestone_date: string;
    description: string;
    status?: MilestoneStatus;
};

export type MilestoneStatus = '正常' | '延期' | '完成';

export type MilestoneUpdate = {
    milestone_date?: (string | null);
    description?: (string | null);
    status?: (MilestoneStatus | null);
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PermissionCreate = {
    name: string;
    resource: string;
    action: string;
    description?: string;
};

export type PermissionPublic = {
    id: string;
    name: string;
    resource: string;
    action: string;
    description?: (string | null);
};

export type PermissionUpdate = {
    name?: string;
    resource?: string;
    action?: string;
    description?: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Progress = {
    description: string;
    progress_type?: ProgressType;
    tracking_user_id: string;
    progress_date?: string;
    id: string;
    project_id: string;
    created_at: string;
    updated_at: string;
};

export type ProgressCreate = {
    description: string;
    progress_type?: ProgressType;
    tracking_user_id: string;
    progress_date?: string;
};

export type ProgressType = '日进展' | '周进展';

export type ProgressUpdate = {
    description?: (string | null);
    progress_type?: (ProgressType | null);
    tracking_user_id?: (string | null);
    progress_date?: (string | null);
};

export type Project = {
    name: string;
    project_type: string;
    location: string;
    contract_amount?: (number | null);
    background?: (string | null);
    import_time?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
    products?: Array<ProjectProduct>;
    role_assignments?: Array<RoleAssignment>;
    milestones?: Array<Milestone>;
    progresses?: Array<Progress>;
};

export type ProjectCountByLocation = {
    location: string;
    count: number;
};

export type ProjectCountByProduct = {
    product: string;
    count: number;
};

export type ProjectCountByType = {
    project_type: string;
    count: number;
};

export type ProjectCreate = {
    name: string;
    project_type: string;
    location: string;
    contract_amount?: (number | null);
    background?: (string | null);
    import_time?: (string | null);
    products?: (Array<ProjectProductCreate> | null);
    role_assignments?: (Array<RoleAssignmentCreate> | null);
    milestones?: (Array<MilestoneCreate> | null);
};

export type ProjectProduct = {
    product_name: string;
    product_amount?: (number | null);
    id: string;
    project_id: string;
    created_at: string;
};

export type ProjectProductCreate = {
    product_name: string;
    product_amount?: (number | null);
};

export type ProjectStatistics = {
    by_location: Array<ProjectCountByLocation>;
    by_product: Array<ProjectCountByProduct>;
    by_type: Array<ProjectCountByType>;
    total_projects: number;
    total_contract_amount: number;
};

export type ProjectUpdate = {
    name?: (string | null);
    project_type?: (string | null);
    location?: (string | null);
    contract_amount?: (number | null);
    background?: (string | null);
    import_time?: (string | null);
    products?: (Array<ProjectProductCreate> | null);
    role_assignments?: (Array<RoleAssignmentCreate> | null);
    milestones?: (Array<MilestoneCreate> | null);
};

export type RoleAssignment = {
    role_name: string;
    user_name: string;
    user_email?: (string | null);
    user_phone?: (string | null);
    user_description?: (string | null);
    id: string;
    project_id: string;
    created_at: string;
};

export type RoleAssignmentCreate = {
    role_name: string;
    user_name: string;
    user_email?: (string | null);
    user_phone?: (string | null);
    user_description?: (string | null);
};

export type RoleCreate = {
    name: string;
    description?: string;
};

export type RolePublic = {
    id: string;
    name: string;
    description?: (string | null);
    permissions?: Array<PermissionPublic>;
};

export type RoleUpdate = {
    name?: string;
    description?: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
};

export type ProjectsCreateProjectResponse = (Project);

export type ProjectsReadProjectsData = {
    limit?: number;
    skip?: number;
};

export type ProjectsReadProjectsResponse = (Array<Project>);

export type ProjectsGetProjectStatisticsResponse = (ProjectStatistics);

export type ProjectsReadProjectData = {
    projectId: string;
};

export type ProjectsReadProjectResponse = (Project);

export type ProjectsUpdateProjectData = {
    projectId: string;
    requestBody: ProjectUpdate;
};

export type ProjectsUpdateProjectResponse = (Project);

export type ProjectsDeleteProjectData = {
    projectId: string;
};

export type ProjectsDeleteProjectResponse = (unknown);

export type ProjectsCreateRoleAssignmentData = {
    projectId: string;
    requestBody: RoleAssignmentCreate;
};

export type ProjectsCreateRoleAssignmentResponse = (RoleAssignment);

export type ProjectsDeleteRoleAssignmentData = {
    projectId: string;
    roleId: string;
};

export type ProjectsDeleteRoleAssignmentResponse = (unknown);

export type ProjectsCreateMilestoneData = {
    projectId: string;
    requestBody: MilestoneCreate;
};

export type ProjectsCreateMilestoneResponse = (Milestone);

export type ProjectsReadProjectMilestonesData = {
    projectId: string;
};

export type ProjectsReadProjectMilestonesResponse = (Array<Milestone>);

export type ProjectsUpdateMilestoneData = {
    milestoneId: string;
    projectId: string;
    requestBody: MilestoneUpdate;
};

export type ProjectsUpdateMilestoneResponse = (Milestone);

export type ProjectsDeleteMilestoneData = {
    milestoneId: string;
    projectId: string;
};

export type ProjectsDeleteMilestoneResponse = (unknown);

export type ProjectsCreateProgressData = {
    projectId: string;
    requestBody: ProgressCreate;
};

export type ProjectsCreateProgressResponse = (Progress);

export type ProjectsReadProjectProgressesData = {
    projectId: string;
};

export type ProjectsReadProjectProgressesResponse = (unknown);

export type ProjectsUpdateProgressData = {
    progressId: string;
    projectId: string;
    requestBody: ProgressUpdate;
};

export type ProjectsUpdateProgressResponse = (Progress);

export type ProjectsDeleteProgressData = {
    progressId: string;
    projectId: string;
};

export type ProjectsDeleteProgressResponse = (unknown);

export type RbacGetRolesWorkingResponse = (Array<RolePublic>);

export type RbacCreateRoleData = {
    requestBody: RoleCreate;
};

export type RbacCreateRoleResponse = (RolePublic);

export type RbacGetPermissionsWorkingResponse = (Array<PermissionPublic>);

export type RbacCreatePermissionData = {
    requestBody: PermissionCreate;
};

export type RbacCreatePermissionResponse = (PermissionPublic);

export type RbacUpdatePermissionData = {
    permissionId: string;
    requestBody: PermissionUpdate;
};

export type RbacUpdatePermissionResponse = (PermissionPublic);

export type RbacDeletePermissionData = {
    permissionId: string;
};

export type RbacDeletePermissionResponse = (unknown);

export type RbacUpdateRoleData = {
    requestBody: RoleUpdate;
    roleId: string;
};

export type RbacUpdateRoleResponse = (RolePublic);

export type RbacDeleteRoleData = {
    roleId: string;
};

export type RbacDeleteRoleResponse = (unknown);

export type RbacAssignPermissionToRoleData = {
    permissionId: string;
    roleId: string;
};

export type RbacAssignPermissionToRoleResponse = (unknown);

export type RbacRemovePermissionFromRoleData = {
    permissionId: string;
    roleId: string;
};

export type RbacRemovePermissionFromRoleResponse = (unknown);

export type RbacGetRolePermissionsData = {
    roleId: string;
};

export type RbacGetRolePermissionsResponse = (Array<PermissionPublic>);

export type RbacAssignRoleToUserData = {
    roleId: string;
    userId: string;
};

export type RbacAssignRoleToUserResponse = (unknown);

export type RbacRemoveRoleFromUserData = {
    roleId: string;
    userId: string;
};

export type RbacRemoveRoleFromUserResponse = (unknown);

export type RbacGetUserRolesData = {
    userId: string;
};

export type RbacGetUserRolesResponse = (Array<RolePublic>);

export type RbacGetUserPermissionsData = {
    userId: string;
};

export type RbacGetUserPermissionsResponse = (Array<PermissionPublic>);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);