"""Add RBAC system

Revision ID: 28b982ca8e4e
Revises: 427fb74cd754
Create Date: 2025-10-18 11:53:23.988424

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '28b982ca8e4e'
down_revision = '427fb74cd754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
