"""add project management system

Revision ID: 466ecd932fbf
Revises: 28b982ca8e4e
Create Date: 2025-10-19 19:13:42.339493

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql
from uuid import uuid4


# revision identifiers, used by Alembic.
revision = '466ecd932fbf'
down_revision = '28b982ca8e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'project',
        sa.Column('id', postgresql.UUID(), nullable=False, default=uuid4),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('project_type', sa.String(), nullable=False),
        sa.Column('location', sa.String(), nullable=False),
        sa.Column('contract_amount', sa.Float(), nullable=True),
        sa.Column('background', sa.String(), nullable=True),
        sa.Column('product', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    
    op.create_table(
        'milestone',
        sa.Column('id', postgresql.UUID(), nullable=False, default=uuid4),
        sa.Column('project_id', postgresql.UUID(), nullable=False),
        sa.Column('milestone_date', sa.DateTime(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table(
        'progress',
        sa.Column('id', postgresql.UUID(), nullable=False, default=uuid4),
        sa.Column('project_id', postgresql.UUID(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('progress_type', sa.String(), nullable=False),
        sa.Column('tracking_user_id', postgresql.UUID(), nullable=False),
        sa.Column('progress_date', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
        sa.ForeignKeyConstraint(['tracking_user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table(
        'role_assignment',
        sa.Column('id', postgresql.UUID(), nullable=False, default=uuid4),
        sa.Column('project_id', postgresql.UUID(), nullable=False),
        sa.Column('role_name', sa.String(), nullable=False),
        sa.Column('user_id', postgresql.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_assignment_role_name'), 'role_assignment', ['role_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_assignment_role_name'), table_name='role_assignment')
    op.drop_table('role_assignment')
    op.drop_table('progress')
    op.drop_table('milestone')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
