"""add_import_time_to_project

Revision ID: 52f61a8d9ff6
Revises: 63cb726cb7c9
Create Date: 2025-10-20 02:52:40.347513

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '52f61a8d9ff6'
down_revision = '63cb726cb7c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('import_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'import_time')
    # ### end Alembic commands ###