"""add_project_products_table

Revision ID: 63cb726cb7c9
Revises: 8308cb3113d4
Create Date: 2025-10-20 00:22:48.842658

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '63cb726cb7c9'
down_revision = '8308cb3113d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 创建项目产品表
    op.create_table('project_product',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # 删除项目表中的product字段
    op.drop_column('project', 'product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 恢复项目表中的product字段
    op.add_column('project', sa.Column('product', sa.VARCHAR(), autoincrement=False, nullable=False))
    # 删除项目产品表
    op.drop_table('project_product')
    # ### end Alembic commands ###
