"""update_role_assignment_table_structure

Revision ID: 69a12b9bb0d3
Revises: 466ecd932fbf
Create Date: 2025-10-19 23:51:28.236202

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '69a12b9bb0d3'
down_revision = '466ecd932fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 只修改 role_assignment 表，不删除 RBAC 相关表
    
    # 先创建枚举类型
    milestone_status_enum = sa.Enum('NORMAL', 'DELAYED', 'COMPLETED', name='milestonestatus')
    progress_type_enum = sa.Enum('DAILY', 'WEEKLY', name='progresstype')
    milestone_status_enum.create(op.get_bind())
    progress_type_enum.create(op.get_bind())
    
    # 修改列类型
    op.alter_column('milestone', 'status',
               existing_type=sa.VARCHAR(),
               type_=milestone_status_enum,
               existing_nullable=False,
               postgresql_using='status::milestonestatus')
    op.alter_column('progress', 'progress_type',
               existing_type=sa.VARCHAR(),
               type_=progress_type_enum,
               existing_nullable=False,
               postgresql_using='progress_type::progresstype')
    
    # 修改 role_assignment 表
    op.add_column('role_assignment', sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('role_assignment', sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('role_assignment', sa.Column('user_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('role_assignment_user_id_fkey'), 'role_assignment', type_='foreignkey')
    op.drop_column('role_assignment', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_assignment', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('role_assignment_user_id_fkey'), 'role_assignment', 'user', ['user_id'], ['id'])
    op.drop_column('role_assignment', 'user_phone')
    op.drop_column('role_assignment', 'user_email')
    op.drop_column('role_assignment', 'user_name')
    op.alter_column('progress', 'progress_type',
               existing_type=sa.Enum('DAILY', 'WEEKLY', name='progresstype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('milestone', 'status',
               existing_type=sa.Enum('NORMAL', 'DELAYED', 'COMPLETED', name='milestonestatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('role_permissions_permission_id_fkey')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('role_permissions_role_id_fkey')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('role_permissions_pkey'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('resource', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('permissions_pkey'))
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('user_roles_role_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_roles_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('user_roles_pkey'))
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('roles_pkey'))
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    # ### end Alembic commands ###
