/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSimpleMuiTestRouteImport } from './routes/_layout/simple-mui-test'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRbacRouteImport } from './routes/_layout/rbac'
import { Route as LayoutMuiRbacRouteImport } from './routes/_layout/mui-rbac'
import { Route as LayoutMuiDemoRouteImport } from './routes/_layout/mui-demo'
import { Route as LayoutMaterialTestRouteImport } from './routes/_layout/material-test'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutHybridDemoRouteImport } from './routes/_layout/hybrid-demo'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSimpleMuiTestRoute = LayoutSimpleMuiTestRouteImport.update({
  id: '/simple-mui-test',
  path: '/simple-mui-test',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRbacRoute = LayoutRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMuiRbacRoute = LayoutMuiRbacRouteImport.update({
  id: '/mui-rbac',
  path: '/mui-rbac',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMuiDemoRoute = LayoutMuiDemoRouteImport.update({
  id: '/mui-demo',
  path: '/mui-demo',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMaterialTestRoute = LayoutMaterialTestRouteImport.update({
  id: '/material-test',
  path: '/material-test',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHybridDemoRoute = LayoutHybridDemoRouteImport.update({
  id: '/hybrid-demo',
  path: '/hybrid-demo',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/test': typeof TestRoute
  '/admin': typeof LayoutAdminRoute
  '/hybrid-demo': typeof LayoutHybridDemoRoute
  '/items': typeof LayoutItemsRoute
  '/material-test': typeof LayoutMaterialTestRoute
  '/mui-demo': typeof LayoutMuiDemoRoute
  '/mui-rbac': typeof LayoutMuiRbacRoute
  '/rbac': typeof LayoutRbacRoute
  '/settings': typeof LayoutSettingsRoute
  '/simple-mui-test': typeof LayoutSimpleMuiTestRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/test': typeof TestRoute
  '/admin': typeof LayoutAdminRoute
  '/hybrid-demo': typeof LayoutHybridDemoRoute
  '/items': typeof LayoutItemsRoute
  '/material-test': typeof LayoutMaterialTestRoute
  '/mui-demo': typeof LayoutMuiDemoRoute
  '/mui-rbac': typeof LayoutMuiRbacRoute
  '/rbac': typeof LayoutRbacRoute
  '/settings': typeof LayoutSettingsRoute
  '/simple-mui-test': typeof LayoutSimpleMuiTestRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/test': typeof TestRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/hybrid-demo': typeof LayoutHybridDemoRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/material-test': typeof LayoutMaterialTestRoute
  '/_layout/mui-demo': typeof LayoutMuiDemoRoute
  '/_layout/mui-rbac': typeof LayoutMuiRbacRoute
  '/_layout/rbac': typeof LayoutRbacRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/simple-mui-test': typeof LayoutSimpleMuiTestRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/test'
    | '/admin'
    | '/hybrid-demo'
    | '/items'
    | '/material-test'
    | '/mui-demo'
    | '/mui-rbac'
    | '/rbac'
    | '/settings'
    | '/simple-mui-test'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/test'
    | '/admin'
    | '/hybrid-demo'
    | '/items'
    | '/material-test'
    | '/mui-demo'
    | '/mui-rbac'
    | '/rbac'
    | '/settings'
    | '/simple-mui-test'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/test'
    | '/_layout/admin'
    | '/_layout/hybrid-demo'
    | '/_layout/items'
    | '/_layout/material-test'
    | '/_layout/mui-demo'
    | '/_layout/mui-rbac'
    | '/_layout/rbac'
    | '/_layout/settings'
    | '/_layout/simple-mui-test'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/simple-mui-test': {
      id: '/_layout/simple-mui-test'
      path: '/simple-mui-test'
      fullPath: '/simple-mui-test'
      preLoaderRoute: typeof LayoutSimpleMuiTestRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rbac': {
      id: '/_layout/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof LayoutRbacRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mui-rbac': {
      id: '/_layout/mui-rbac'
      path: '/mui-rbac'
      fullPath: '/mui-rbac'
      preLoaderRoute: typeof LayoutMuiRbacRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mui-demo': {
      id: '/_layout/mui-demo'
      path: '/mui-demo'
      fullPath: '/mui-demo'
      preLoaderRoute: typeof LayoutMuiDemoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/material-test': {
      id: '/_layout/material-test'
      path: '/material-test'
      fullPath: '/material-test'
      preLoaderRoute: typeof LayoutMaterialTestRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/hybrid-demo': {
      id: '/_layout/hybrid-demo'
      path: '/hybrid-demo'
      fullPath: '/hybrid-demo'
      preLoaderRoute: typeof LayoutHybridDemoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutHybridDemoRoute: typeof LayoutHybridDemoRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutMaterialTestRoute: typeof LayoutMaterialTestRoute
  LayoutMuiDemoRoute: typeof LayoutMuiDemoRoute
  LayoutMuiRbacRoute: typeof LayoutMuiRbacRoute
  LayoutRbacRoute: typeof LayoutRbacRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSimpleMuiTestRoute: typeof LayoutSimpleMuiTestRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutHybridDemoRoute: LayoutHybridDemoRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutMaterialTestRoute: LayoutMaterialTestRoute,
  LayoutMuiDemoRoute: LayoutMuiDemoRoute,
  LayoutMuiRbacRoute: LayoutMuiRbacRoute,
  LayoutRbacRoute: LayoutRbacRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSimpleMuiTestRoute: LayoutSimpleMuiTestRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
